lenguage: java
jdk: openjdk11

addons:
  sonarcloud:
    organization: "viniciusbenite"
    token: ${SONAR_TOKEN}

script:
  - ./mvnw clean install -B
  - ./mvnw clean verify sonar:sonar -Pcoverage

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'