lenguage: java
jdk: openjdk11

addons:
  sonarcloud:
    organization: "viniciusbenite"
    token: ${SONAR_TOKEN}

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - ./mvnw package spring-boot:repackage
  - ./mvnw clean install -B
  - ./mvnw clean verify sonar:sonar -Pcoverage

deploy:
  provider: heroku
  api_key:
    secure: q02+FYaHF5LGke0ZThu1cDjw66b6Bn8Z8nYzBcX6zqqyov5mVuP8bNAT4G8AY7M43YdBBJ9YUvIf0ZnO+1vKHRrh5Hpqb0p66Fov3A/YF9c9zfhEzcQXTvjkMvHK9Y8jm0Ttc9efUr8GE8tIK3DR6+iD6eZfA6fwUZl1ZRqeH1NQqoNLvVRLSda2yuhIMIhimz4qdGcJVPRiSiei1dlneBRtnMV1IBof6FOCtpnnR6fH34QCJ1iEtwz3fzUvRPfABze0gi4DN5D2rAs894IkfygXNeG4s5v43ftS1P9P7zcFFwNOFbx+OHnQgp2tBpDIrTKtSn44Qs2WZZ6vB7uHiG5+3jtiYj4+bUimOEHixsechgEdEn9Ss2fqZp/NjMGXNb8ld0zyxiN2/yxjQCmrl6wo+JFU7bek8X4Xyg7rvQ3tmUgnZKZMaEObEhV28VlavOcoeUZ2hlzZqrpVD+1ltg4uuOh71EKx+xbrvWHwD3TCQYa0Q7rYUsMGpp1Si0v96CVYYjfAMEztv/zDa5giwsDgAUM/HgogLX8dmZZw/4WpTYtWnnvBAZ5IyKvz9UqBckXwsZd9NfNchMitn1+lU01Su41BaSDlCK5g0w9H/6YwKNBi/Ia2J87HpTk0P3dBjHL1pCPWeJrWSn503rXlebpFlZRgFg9raOE2v+i2H9s=
  app: tqs-final-project-barbershop
  on:
    all_branches: true