lenguage: java
jdk: openjdk11

addons:
  sonarcloud:
    organization: "viniciusbenite"
    token: ${SONAR_TOKEN}

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

sudo: required

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - chmod +rwx ./.travis/main.sh
  - './.travis/main.sh'
  - docker pull openjdk:11-jdk-slim

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=barbershop/barbershop-app:0.1-SNAPSHOP
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME

script:
  - 'docker version'
  - ./mvnw package spring-boot:repackage
  - ./mvnw clean install -B
  - ./mvnw clean verify sonar:sonar -Pcoverage
