matrix:
  include:
    - lenguage: java
      jdk: openjdk8
      addons:
        sonarcloud:
          organization: viniciusbenite
          token: "${SONAR_TOKEN}"
      sudo: required
      cache:
        directories:
          - "$HOME/.m2/repository"
          - "$HOME/.sonar/cache"
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      before_install:
        - chmod a+x ./mvnw
      script:
        - "./mvnw clean install -B"
        - "./mvnw clean verify sonar:sonar -Pcoverage"
      deploy:
        provider: heroku
        api_key:
          secure: jWqg4s1rkwyNgMTwK3I4t6lh4/IbfaRS3NL3oiHRfRYFYywPxQCvMMUUnG7ACrYOv/K1OtbdaROcT8/h5iuefOIREl6NJnMsKuHsqwVjsO6bVZxCQGWljOrigEdTAcoJdg7JRzK7seUtbZ2eE+nHm/2Nx2I4YPeWc8abNspEiiqGO1Y06TEAq7IDJFzbAau4Y4JS9MbUvy/QH5SHw8eQ85fsm+YzHtGkX125sct+R9HsmyCaicCe6BBtiScaHWHVYDvXbxSdRGOwKfDgFXZrzOs1lqawieHtHypQhJ0LJvMNyGAF/EOfViqWsCQAERkOTP7IUJXWpWTjxYb8ClGr62hnMMG+Mk2SzqlE1Txru9qGCevVkbCDTevmyLpVmVlqfz3M6Clcp+Vtg+g9+RqR2ChGZ2HvNtQpKE/irULS+xFU4doIyt2mcqD0yM6Pocy8Jbz3DBxZMMKTBhO85R82v0yscrkDn3O3io81vgTXzE6AWQMgi2GVmiG3oN6+ei6INzR1ALaiizHLkvRlwwI5mhngCbUtpT7pw+7TgjOFM9fLs01DW/EHecWSP6DzSmiNN0iNPFXf07JvD04Tz/o2KRNdaUbSAqOvNBfLGRuWgEv6NR/iap6peWFpQShlQt4QXtsXcR4xNKhdgHhb8e6v1RyF+C+Sk+HnIR6/GDUS/8I=
        app: tqs-final-project-barbershop
        on:
          all_branches: true

      - lenguage: dart
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - libstdc++6
              - fonts-droid-fallback
        before_script:
          - cd mobile_app
          - sudo apt-get install -y --no-install-recommends lib32stdc++6 libstdc++6 > /dev/null
          - FLUTTER_CHANNEL=stable
          - FLUTTER_VERSION=1.12.13+hotfix.9-${FLUTTER_CHANNEL}
          - wget --quiet --output-document=flutter.tar.xz https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/linux/flutter_linux_v${FLUTTER_VERSION}.tar.xz && tar xf flutter.tar.xz > /dev/null && rm flutter.tar.xz
          - export PATH="$PATH":"$HOME/.pub-cache/bin"
          - export PATH=$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH
          - flutter doctor -v
        script:
          - flutter drive --terget=test_driver/app.dart
        cache:
          directories:
            - $HOME/.pub-cache


