lenguage: java
jdk: openjdk11

addons:
  sonarcloud:
    organization: "viniciusbenite"
    token: ${SONAR_TOKEN}

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

sudo: required

services:
  - docker

before_install:
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin registry.example.com
  - docker pull openjdk:11-jdk-slim

script:
  - ./mvnw clean install -B
  - ./mvnw clean verify sonar:sonar -Pcoverage
  - ./mvnw deploy
