lenguage: java
jdk: openjdk11
addons:
  sonarcloud:
    organization: "viniciusbenite"
    token:
      secure: "c942ca09d6996c6b0b107b0a2ae4f3def41b673f"

script:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar